# monitoring/fluentbit-values.yaml

cloudWatchLogs:
  enabled: true
  region: us-east-1
  logGroupName: /aws/containerinsights/eks-alain/application
  autoCreateGroup: true

serviceAccount:
  create: false # On passe à false car eksctl l'a déjà créé
  name: aws-for-fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/FluentBitCloudWatchRole